using UnityEngine;

/// <summary>
/// A factory for initializing new portable items based on the factories
/// serialized array of item details.
/// </summary>
[CreateAssetMenu(fileName="New Portable Item Factory", menuName="Scriptable Objects/Factories/Portable Item Factory")]
public class PortableItemFactory : ScriptableObject {
  /// <summary>
  /// An array of details for items that can be generated by this factory.
  /// </summary>
  public PortableItemDetails[] items;

  /// <summary>
  /// Creates a random item from the list of possible items.
  /// </summary>
  /// <returns>
  /// A new <c>PortableItem</c> based on the randomly selected details.
  /// </returns>
  public PortableItem CreateRandomItem() {
    PortableItem item = ScriptableObject.CreateInstance<PortableItem>();
    item.details = items[StaticRandom.Range(0, items.Length)];
    return item;
  }
}